import { useSelector } from "react-redux";
import { BsFileArrowUpFill } from "react-icons/bs";
import ScrollToTop from "react-scroll-up";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Social from "../components/Social";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

const Home = () => {
  const notify = () => {
    toast.success("Thanks for your message!", {
      position: "top-right",
      autoClose: 5000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "colored",
    });
  };

  const darkMode = useSelector((state) => state.darkMode.isDarkMode);
  return (
    <div id="home" className={darkMode ? "dark" : ""}>
      <nav>
        <title>Zin Lin Htet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </nav>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-10">
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
        />
        <Social />
        <Hero />
        <About />
        <Skills />
        <Contact notify={notify} />
        <ScrollToTop showUnder={160}>
          <BsFileArrowUpFill className="text-5xl text-cyan-500 mr-1" />
        </ScrollToTop>
        <Footer className="" />
      </main>
    </div>
  );
};

export default Home;
