import Navbar from "./Navbar";
import { useSelector } from "react-redux";
import Hero from "./Hero";
import About from "./About";
import Projects from "./Projects";
import Contact from "./Contact";
import { BsFileArrowUpFill } from "react-icons/bs";
import ScrollToTop from "react-scroll-up";

const Home = () => {

  const darkMode = useSelector((state) => state.darkMode.isDarkMode);
  return (
    <div id="home" className={darkMode ? "dark" : ""}>
      <nav>
        <title>Zin Lin Htet's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </nav>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-10">
        <Navbar />
        <Hero />
        <About />
        <Projects />
        <Contact />
        <ScrollToTop showUnder={160}>
            <BsFileArrowUpFill className="text-4xl " />
        </ScrollToTop>
      </main>
    </div>
  );
};

export default Home;
